name: Landing Page Deployment

on:
  push:
    branches:
      - dev
      - main

jobs:
  BuildLandingPage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: build landing page
        run: |
          cd landing-page
          npm install 
          npm run build

      - name: Upload landing-page artifact
        uses: actions/upload-artifact@v3
        with:
          name: landing-page-artifact
          path: landing-page/build
          retention-days: 1

  Deploy:
    runs-on: ubuntu-latest
    needs: 
      - BuildLandingPage
    steps:
      - uses: actions/checkout@v3

      - name: Download landing page artifact
        uses: actions/download-artifact@v3
        with:
          name: landing-page-artifact
          path: landing-page/build

      - name: install/configure cdk
        run: |
          npm install -g aws-cdk 
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}  --profile default
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile default
          aws configure set default.region us-east-1 --profile default
              
      - name: deploy backend
        run: |
          mv landing-page/build aws/
          cd aws
          npm install
          export STAGE=${GITHUB_REF##*/}
          export AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}
          export AIRTABLE_ACCESS_TOKEN=${{ secrets.AIRTABLE_ACCESS_TOKEN }}
          export OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          export OPENAI_ORG_ID=${{ secrets.OPENAI_ORG_ID }}
          cdk deploy --all --outputs-file output.json --require-approval never
      
      - name: Upload cdk output artifact
        uses: actions/upload-artifact@v3
        with:
          name: cdk-output-artifact
          path: ./output.json
          retention-days: 1

  